Publish the charm to charmhub
canonical/hardware-api pull request #106
Opened 2024-04-21 16:45 UTC by mz2

2024-04-29 15:58 UTC, plars requested changes

2024-04-29 15:58 UTC, plars commented on server/charm/metadata.yaml
> +
The build failure should be resolvable by removing the containers section from charmcraft.yaml

2024-05-01 12:50 UTC, mz2 commented on .github/workflows/publish_server.yml
> +          charm-path: "./server/charm"
Indeed no practical effect, but let's be consistent. Fixed.

2024-05-01 12:52 UTC, mz2 commented on .github/workflows/publish_server.yml
> +    branches: ["main", "charm-publishing"]
Yep, will remove once there's one successful build.

2024-05-01 20:50 UTC, plars approved these changes
Ok, I at least got it to push to the charmstore now. The errors made no sense so I tried pushing it manually using the same credentials and it worked. After that, it was able to push the resource. So I'm wondering if maybe the charm has to be pushed at least once before the resource is pushed? but that won't work with the action alone because when the charm is pushed it also ties it to the resource for the release...
There are still errors, but I was at least able to confirm that the charm is in the store successfully now. So let's merge this and then we can keep iterating on it.

2024-05-01 20:50 UTC, merged