License additions
canonical/hardware-api pull request #245
Opened 2024-11-22 12:20 UTC by jocave

Appropriate open source licenses should be applied to the separate components contained within this monorepo.

2024-11-22 14:31 UTC, jocave commented
Request for @nadzyah to check the file headers match the license files and add to this branch before taking out of draft status

2024-11-26 09:25 UTC, omar-selo commented on client/hwlib/src/collectors/cpuinfo.rs
> + * it under the terms of the GNU Lesser General Public License as published by
Looking at https://sites.google.com/a/canonical.com/operations/legal/software-licensing it seems that we should also include the license version with it?

2024-11-26 09:29 UTC, omar-selo requested changes

2024-11-26 09:29 UTC, omar-selo commented on client/hwlib/src/collectors/cpuinfo.rs
> + * You should have received a copy of the GNU Lesser General Public License
Reading https://sites.google.com/a/canonical.com/operations/legal/software-licensing it seems that we want to ensure that we use version 3 and not version or any later version

2024-11-26 13:28 UTC, merged