Make integration tests to be snapshot tests
canonical/hardware-api pull request #247
Opened 2024-11-22 13:26 UTC by nadzyah

2024-11-25 08:06 UTC, omar-selo commented on server/hwapi/data_models/repository.py
> +                ),
why not add `.lower` to `_clean_vendor_name` function?

2024-11-25 08:11 UTC, omar-selo commented
I've been thinking about this over the weekend and I think it would make sense if these tests which run part as part of hardware API CI only test hardware API and not C3 in any way. If we want an integration test between C3 and hardware API that should be triggered whenever a change occurs in this repo or C3's. But in this case this integration test is just for hardware API. So perhaps we shouldn't fetch anything from C3. Instead it would make sense to go with the option you proposed to me on MM in which we store the expected partial C3 response. This way we'd test hardware API all the way starting from retrieving data from C3 (albeit mocked). wdyt?

2024-11-26 12:45 UTC, omar-selo requested changes

2024-11-26 12:45 UTC, omar-selo commented on server/scripts/import_test_data_from_c3.py
what do you think of moving `import_test_data_from_c3.py` and the related json files from `c3_test_data` into `integration-tests` directory?

2024-11-26 13:03 UTC, nadzyah commented on server/scripts/import_test_data_from_c3.py
it would be challenging since the docker container that we set up for the server works in the `server/` directory context

2024-11-26 13:10 UTC, omar-selo commented on server/scripts/import_test_data_from_c3.py
Can you rename the file `import_test_data_from_c3`? it's a bit misleading

2024-11-26 13:27 UTC, nadzyah commented on server/scripts/import_test_data_from_c3.py
what name do you prefer?

2024-11-27 17:12 UTC, merged